version: '3'
services:

    #Nginx Service
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8077:80"
        container_name: pugslarvue_nginx
        depends_on:
            - app

    #PHP Service
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: pugslarvue_app
        depends_on:
            - mysql
        environment:
            REDIS_HOST: "redis"
            REDIS_PORT: ${REDIS_PORT}

    #MySQL Service
    mysql:
        image: mysql:8.0
        container_name: pugslarvue_db
        restart: always
        volumes:
            - ./tmp/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: passwordPugs
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: pugslaravelvue
        ports:
            - "8111:8111"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --port=8111

    #Redis Service
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: project_redis
        restart: always
        volumes:
            - ./tmp/db/redis:/var/lig/redis
